CREATE TABLE IF NOT EXISTS 'users' 
        ('id' INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
        'username' TEXT NOT NULL, 
        'hash' INT NOT NULL);
CREATE TABLE IF NOT EXISTS 'tasks'
    ('id' INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	'user_id' TEXT NOT NULL,
    'title' TEXT NOT NULL,
    'date' TEXT NOT NULL,
    'freq' INT NOT NULL DEFAULT 1,
    'complete' INT NOT NULL DEFAULT 0,
    FOREIGN KEY(user_id) REFERENCES users(id));